/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { TestContractFactory } from "./TestContractFactory";
export type { TestContract } from "./TestContract";
export { TestContract1Factory } from "./TestContract1Factory";
export type { TestContract1 } from "./TestContract1";
